<Project>
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>preview</AnalysisLevel>

        <!-- Package metadata -->
        <Version>1.0.5</Version>
        <Authors>Taiizor</Authors>
        <Company>Taiizor</Company>
        <Product>Cici - Flaky Test Detector</Product>
        <Copyright>Copyright © 2025 Taiizor</Copyright>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/Taiizor/Cici</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Taiizor/Cici</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>testing;flaky;test;automation;ci;quality;xunit;nunit;mstest</PackageTags>
        <PackageIcon>icon.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup Condition="'$(IsPackable)' == 'true'">
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="\" />
        <None Include="$(MSBuildThisFileDirectory)icon.png" Pack="true" PackagePath="icon.png" />
    </ItemGroup>
</Project>