<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackAsTool>true</PackAsTool>
        <AnalysisLevel>preview</AnalysisLevel>
        <LangVersion>preview</LangVersion>
        <ToolCommandName>cici</ToolCommandName>
        <PackageOutputPath>./nupkg</PackageOutputPath>
        <AssemblyName>cici-cli</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cici\Cici.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Spectre.Console" Version="0.48.0" />
    </ItemGroup>

</Project>
